apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: maroos-club-tls
spec:
  secretKey: maroos-club
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: maroos.club
  dnsNames:
    - maroos.club
    - www.maroos.club
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - maroos.club
          - www.maroos.club